version: '3'

services:

  # database containers, one for each db
  ecotaxa_database:
    image: postgres:11
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    expose:
        - "5432"
    ports:
        - "5432:5432"
    env_file:
      - config/db/ecotaxa_env
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4:latest
    # doc is in https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    # so, after it fails once, do: sudo chown -R 5050:5050 ./pgadmin
    environment:
        - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
        - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
        - "PGADMIN_LISTEN_ADDRESS=0.0.0.0"
#        - "PGADMIN_LISTEN_PORT=80"
#        - "PGADMIN_CONFIG_DEBUG=True"
#        - "PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10"
    ports:
        - "5050:80"
    volumes:
        - ./pgadmin:/var/lib/pgadmin
    depends_on:
        - ecotaxa_database
    networks:
        - db_network

networks:
  db_network:
    driver: bridge

volumes:
  db_volume:
    driver: local

