""" top-n migration cleanup

Revision ID: 032dfb7159d5
Revises: 4045b161563b
Create Date: 2024-11-28 09:09:26.127567

"""

# revision identifiers, used by Alembic.
revision = "032dfb7159d5"
down_revision = "4045b161563b"

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dropped_process_26032024")
    op.drop_table("objectsclassifhisto_old")
    op.drop_table("proj_with_incon")
    op.drop_index("mig_obj_prj2_objid_classif_auto_when_idx", table_name="mig_obj_prj2")
    op.drop_index("mig_obj_prj2_projid_objid_idx", table_name="mig_obj_prj2")
    op.drop_table("mig_obj_prj2")
    op.drop_index("is_objectsacqclassifqual_old", table_name="obj_head_old")
    op.drop_index("is_objectsacquisition_old", table_name="obj_head_old")
    op.drop_index("is_objectsdate_old", table_name="obj_head_old")
    op.drop_index("is_objectsdepth_old", table_name="obj_head_old")
    op.drop_index("is_objectslatlong_old", table_name="obj_head_old")
    op.drop_index("is_objectstime_old", table_name="obj_head_old")
    op.drop_table("obj_head_old")
    op.drop_index("mig_obj_prj_projid_objid_idx", table_name="mig_obj_prj")
    op.drop_table("mig_obj_prj")
    op.drop_index(
        "mig_classif_tasks_projid_begin_date_end_date_idx",
        table_name="mig_classif_tasks",
    )
    op.drop_table("mig_classif_tasks")
    op.drop_table("dropped_samples_26032024")
    op.drop_table("dropped_acquisitions_26032024")
    op.drop_table("mig_states_04_10_2024")
    op.drop_table("mig_classif_chunks_per_proj")
    op.drop_table("mig_unq_classif_per_proj")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
