"""WoRMS

Revision ID: 08807338f98d
Revises: fc9fb059120c
Create Date: 2026-01-11 06:57:31.852208

"""

# revision identifiers, used by Alembic.
revision = "08807338f98d"
down_revision = "fc9fb059120c"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("worms_pp", table_name="worms")
    op.drop_table("worms")
    op.add_column("taxonomy", sa.Column("aphia_id", sa.INTEGER(), nullable=True))
    op.add_column("taxonomy", sa.Column("rank", sa.VARCHAR(length=24), nullable=True))
    op.drop_index("IS_TaxonomySource", table_name="taxonomy")
    op.create_index("IS_TaxonomyAphiaId", "taxonomy", ["aphia_id"], unique=False)
    op.drop_column("taxonomy", "id_source")
    # op.drop_table('collection_orga_role_w_organization')
    # op.create_index('obj_cnn_features_vector_hv_ivfflat_l2_5k_idx', 'obj_cnn_features_vector', ['features'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 5000})
    # op.drop_column('projects', 'license')
    # op.drop_column('projects', 'visible')
    # op.alter_column('users', 'type',
    #            existing_type=sa.VARCHAR(length=10),
    #            nullable=True)
    # op.drop_column('users', 'organization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "taxonomy",
        sa.Column(
            "id_source", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    op.drop_index("IS_TaxonomyAphiaId", table_name="taxonomy")
    op.create_index("IS_TaxonomySource", "taxonomy", ["id_source"], unique=False)
    op.drop_column("taxonomy", "rank")
    op.drop_column("taxonomy", "aphia_id")
    op.create_table(
        "worms",
        sa.Column("aphia_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "scientificname", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column(
            "authority", sa.VARCHAR(length=385), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.VARCHAR(length=24), autoincrement=False, nullable=True),
        sa.Column(
            "unacceptreason", sa.VARCHAR(length=768), autoincrement=False, nullable=True
        ),
        sa.Column("taxon_rank_id", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.Column("rank", sa.VARCHAR(length=24), autoincrement=False, nullable=True),
        sa.Column("valid_aphia_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "valid_name", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column(
            "valid_authority",
            sa.VARCHAR(length=386),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "parent_name_usage_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "kingdom", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column("phylum", sa.VARCHAR(length=129), autoincrement=False, nullable=True),
        sa.Column("class_", sa.VARCHAR(length=130), autoincrement=False, nullable=True),
        sa.Column("order", sa.VARCHAR(length=131), autoincrement=False, nullable=True),
        sa.Column("family", sa.VARCHAR(length=132), autoincrement=False, nullable=True),
        sa.Column("genus", sa.VARCHAR(length=133), autoincrement=False, nullable=True),
        sa.Column(
            "citation", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column("lsid", sa.VARCHAR(length=257), autoincrement=False, nullable=True),
        sa.Column("is_marine", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_brackish", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_freshwater", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_terrestrial", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_extinct", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "match_type", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
        sa.Column(
            "modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("all_fetched", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("aphia_id", name="worms_pkey"),
    )
    op.create_index(
        "worms_pp", "worms", ["parent_name_usage_id", "aphia_id"], unique=False
    )
    # op.add_column(
    #     "projects",
    #     sa.Column("visible", sa.BOOLEAN(), autoincrement=False, nullable=True),
    # )
    # op.add_column(
    #     "projects",
    #     sa.Column(
    #         "license",
    #         sa.VARCHAR(length=16),
    #         server_default=sa.text("''::character varying"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    # )
    # op.drop_index(
    #     "obj_cnn_features_vector_hv_ivfflat_l2_5k_idx",
    #     table_name="obj_cnn_features_vector",
    #     postgresql_using="ivfflat",
    #     postgresql_with={"lists": 5000},
    # )
    # op.create_table(
    #     "collection_orga_role_w_organization",
    #     sa.Column("collection_id", sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.Column(
    #         "organization", sa.VARCHAR(length=255), autoincrement=False, nullable=True
    #     ),
    #     sa.Column("role", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    #     sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
    # )
    # ### end Alembic commands ###
