"""create cnnfeature table with pgvector snd try 19 02 24

Revision ID: 1290ec07eef2
Revises: 1b1beb672279
Create Date: 2024-02-19 11:55:08.810123

"""

# revision identifiers, used by Alembic.
revision = '1290ec07eef2'
down_revision = '1b1beb672279'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obj_cnn_features')
    op.create_foreign_key(None, 'obj_cnn_features_vector', 'obj_head', ['objcnnid'], ['objid'], ondelete='CASCADE')
    op.alter_column('user_password_reset', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('user_password_reset_user_id_fkey', 'user_password_reset', type_='foreignkey')
    op.create_foreign_key(None, 'user_password_reset', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_password_reset', type_='foreignkey')
    op.create_foreign_key('user_password_reset_user_id_fkey', 'user_password_reset', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_password_reset', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'obj_cnn_features_vector', type_='foreignkey')

    op.create_table('obj_cnn_features',
    sa.Column('objcnnid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cnn01', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn02', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn03', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn04', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn05', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn06', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn07', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn08', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn09', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn10', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn11', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn12', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn13', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn14', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn15', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn16', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn17', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn18', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn19', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn20', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn21', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn22', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn23', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn24', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn25', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn26', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn27', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn28', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn29', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn30', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn31', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn32', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn33', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn34', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn35', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn36', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn37', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn38', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn39', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn40', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn41', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn42', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn43', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn44', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn45', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn46', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn47', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn48', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn49', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('cnn50', sa.REAL(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['objcnnid'], ['obj_head.objid'], name='obj_cnn_features_objcnnid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('objcnnid', name='obj_cnn_features_pkey')
    )
    # ### end Alembic commands ###
