"""empty message

Revision ID: 16b84aae414
Revises: 550d613584f
Create Date: 2015-08-13 06:39:13.609813

"""

# revision identifiers, used by Alembic.
revision = '16b84aae414'
down_revision = '550d613584f'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_taxo',
    sa.Column('idtaxo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('idparent', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.CHAR(length=1), nullable=True),
    sa.Column('typetaxo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('idfinal', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('idtaxo')
    )
    op.create_index('IS_TempTaxoIdFinal', 'temp_taxo', ['idfinal'], unique=False)
    op.create_index('IS_TempTaxoParent', 'temp_taxo', ['idparent'], unique=False)
    op.create_index('IS_TaxonomySource', 'taxonomy', ['id_source'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IS_TempTaxoParent', table_name='temp_taxo')
    op.drop_index('IS_TempTaxoIdFinal', table_name='temp_taxo')
    op.drop_index('IS_TaxonomySource', table_name='taxonomy')
    op.drop_table('temp_taxo')
    ### end Alembic commands ###
