"""empty message

Revision ID: 17b02b46329
Revises: 1e0cb48947c
Create Date: 2015-06-15 21:37:27.145224

"""

# revision identifiers, used by Alembic.
revision = "17b02b46329"
down_revision = "1e0cb48947c"

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "objects", sa.Column("classif_crossvalidation_id", sa.INTEGER(), nullable=True)
    )
    op.add_column("objects", sa.Column("random_value", sa.INTEGER(), nullable=True))
    op.create_index(
        "IS_ObjectsRandom",
        "objects",
        ["random_value", "projid", "classif_qual"],
        unique=False,
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IS_ObjectsRandom", table_name="objects")
    op.drop_column("objects", "random_value")
    op.drop_column("objects", "classif_crossvalidation_id")
    ### end Alembic commands ###
