"""users validation

Revision ID: 1b1beb672279
Revises: 34d91185174c
Create Date: 2023-09-08 16:29:27.440565

"""

# revision identifiers, used by Alembic.
revision = "1b1beb672279"
down_revision = "34d91185174c"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reset_user_password",
        sa.Column("user_id", sa.INTEGER(), sa.Identity(always=True), nullable=False),
        sa.Column("temp_password", sa.VARCHAR(), nullable=False),
        sa.Column(
            "creation_date",
            postgresql.TIMESTAMP(),
            default=postgresql.current_timestamp,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.add_column(
        "users",
        sa.Column("status_admin_comment", sa.VARCHAR(255), nullable=True),
    )
    op.add_column(
        "users", sa.Column("status_date", postgresql.TIMESTAMP(), nullable=True)
    )
    op.execute("""ALTER TABLE users ALTER active DROP DEFAULT;""")
    op.execute(
        """ALTER TABLE users ALTER active TYPE SMALLINT
        USING
        CASE
        WHEN status=false THEN 0 ELSE 1
        END;"""
    )
    op.execute("""ALTER TABLE users ALTER active SET DEFAULT 1;""")
    op.execute("""ALTER TABLE users RENAME COLUMN active TO status ;""")
    # alter mail_status from char  to bool
    op.execute("""ALTER TABLE users ALTER mail_status DROP DEFAULT;""")
    op.execute(
        """ALTER TABLE users ALTER mail_status TYPE BOOLEAN
        USING
        CASE
        WHEN mail_status='V' THEN true
        WHEN mail_status='W' then false
        ELSE NULL
        END;"""
    )
    op.execute("""ALTER TABLE users ALTER mail_status SET DEFAULT NULL;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reset_user_password")
    op.drop_column("users", "status_date")
    op.drop_column("users", "status_admin_comment")
    op.execute("""ALTER TABLE users ALTER status DROP DEFAULT;""")
    op.execute(
        """ALTER TABLE users ALTER status TYPE BOOLEAN
    USING
    CASE
    WHEN status=1 THEN true ELSE false
    END;"""
    )
    op.execute("""ALTER TABLE users ALTER status SET DEFAULT true;""")
    op.execute("""ALTER TABLE users RENAME COLUMN status TO active ;""")
    # alter mail_status from bool to char
    op.execute("""ALTER TABLE users ALTER mail_status DROP DEFAULT;""")
    op.execute(
        """ALTER TABLE users ALTER mail_status TYPE CHAR
        USING
        CASE
        WHEN mail_status=true THEN 'V'
        WHEN mail_status=false then 'W'
        ELSE ' '
        END;"""
    )
    op.execute("""ALTER TABLE users ALTER mail_status SET DEFAULT " ";""")
    # ### end Alembic commands ###
