"""User preferences per project

Revision ID: 1be2ade9f03b
Revises: 2788210a1294
Create Date: 2020-09-10 10:19:37.259021

"""

# revision identifiers, used by Alembic.
revision = '1be2ade9f03b'
down_revision = '2788210a1294'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('json_prefs', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
