"""empty message

Revision ID: 1cd3a6d8bef4
Revises: a1bb3311036c
Create Date: 2018-11-05 17:17:51.221769

"""

# revision identifiers, used by Alembic.
revision = "1cd3a6d8bef4"
down_revision = "a1bb3311036c"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countrylist",
        sa.Column("countryname", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("countryname"),
    )
    op.add_column("users", sa.Column("country", sa.String(length=50), nullable=True))
    op.add_column(
        "users", sa.Column("usercreationdate", postgresql.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("usercreationreason", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###
    op.execute(
        """with r as (select min(id) id from roles where name like '%roject creator')
INSERT into users_roles(user_id, role_id)
select distinct member,r.id
from projectspriv pp,r
where privilege='Manage'
and not exists(select 1 from users_roles ur,r where ur.user_id=pp.member and ur.role_id=r.id)
"""
    )
    op.execute(
        "update roles set name='Project creator' where name='Particle module project creator'"
    )
    op.execute(
        """INSERT INTO countrylist(countryname) VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('America'),
('Andorra'),
('Angola'),
('Antigua'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bissau'),
('Bolivia'),
('Bosnia'),
('Botswana'),
('Brazil'),
('British'),
('Brunei'),
('Bulgaria'),
('Burkina'),
('Burma'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cape Verde'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo'),
('Costa Rica'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech'),
('Denmark'),
('Djibouti'),
('Dominica'),
('East Timor'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Emirate'),
('England'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Great Britain'),
('Greece'),
('Grenada'),
('Grenadines'),
('Guatemala'),
('Guinea'),
('Guyana'),
('Haiti'),
('Herzegovina'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Ivory Coast'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Korea'),
('Kosovo'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Rwanda'),
('Samoa'),
('San Marino'),
('Sao Tome'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon'),
('Somalia'),
('South Africa'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('St. Kitts'),
('St. Lucia'),
('St Kitts'),
('St Lucia'),
('Saint Kitts'),
('Santa Lucia'),
('Sudan'),
('Suriname'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Tobago'),
('Togo'),
('Tonga'),
('Trinidad'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Kingdom'),
('United States'),
('Uruguay'),
('USA'),
('Uzbekistan'),
('Vanuatu'),
('Vatican'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe')
"""
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "usercreationreason")
    op.drop_column("users", "usercreationdate")
    op.drop_column("users", "country")
    op.drop_table("countrylist")
    # ### end Alembic commands ###
