"""empty message

Revision ID: 21bb404620d5
Revises: 271c5fddefbf
Create Date: 2021-02-09 12:15:03.993933

"""

# revision identifiers, used by Alembic.
revision = '21bb404620d5'
down_revision = '271c5fddefbf'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_file',
    sa.Column('path', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.CHAR(), server_default='?', nullable=False),
    sa.Column('digest_type', sa.CHAR(), server_default='?', nullable=False),
    sa.Column('digest', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('path')
    )
    op.create_index('is_phy_image_file', 'image_file', ['digest_type', 'digest'], unique=False)
    op.create_index('is_image_file', 'images', ['file_name'], unique=False)
    op.add_column('users', sa.Column('mail_status', sa.CHAR(), server_default=' ', nullable=True))
    op.add_column('users', sa.Column('mail_status_date', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mail_status_date')
    op.drop_column('users', 'mail_status')
    op.drop_index('is_image_file', table_name='images')
    op.drop_index('is_phy_image_file', table_name='image_file')
    op.drop_table('image_file')
    # ### end Alembic commands ###
