"""Add indexes for deletion

Revision ID: 2788210a1294
Revises: 5b2908d16916
Create Date: 2020-09-09 07:08:46.010878

"""

# revision identifiers, used by Alembic.
revision = '2788210a1294'
down_revision = '5b2908d16916'

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('is_objectsacquisition', 'obj_head', ['acquisid'], unique=False)
    op.create_index('is_objectsprocess', 'obj_head', ['processid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('is_objectsprocess', table_name='obj_head')
    op.drop_index('is_objectsacquisition', table_name='obj_head')
    # ### end Alembic commands ###
