"""display order for collections users and organisations

Revision ID: 287303b6d65c
Revises: 08807338f98d
Create Date: 2026-01-20 11:53:59.597333

"""

# revision identifiers, used by Alembic.
revision = '287303b6d65c'
down_revision = '08807338f98d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_orga_role', sa.Column('display_order', sa.INTEGER(), nullable=True))
    op.add_column('collection_user_role', sa.Column('display_order', sa.INTEGER(), nullable=True))
    #op.drop_column('projects', 'visible')
    #op.drop_column('projects', 'license')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('projects', sa.Column('license', sa.VARCHAR(length=16), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    #op.add_column('projects', sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('collection_user_role', 'display_order')
    op.drop_column('collection_orga_role', 'display_order')
    # ### end Alembic commands ###