"""empty message

Revision ID: 28ee72b54d2
Revises: 35177c28cb
Create Date: 2015-07-29 14:35:02.671875

"""

# revision identifiers, used by Alembic.
revision = '28ee72b54d2'
down_revision = '35177c28cb'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectsclassifhisto',
    sa.Column('objid', sa.BIGINT(), nullable=False),
    sa.Column('classif_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('classif_type', sa.CHAR(length=1), nullable=True),
    sa.Column('classif_id', sa.INTEGER(), nullable=True),
    sa.Column('classif_qual', sa.CHAR(length=1), nullable=True),
    sa.Column('classif_who', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classif_who'], ['users.id'], ),
    sa.ForeignKeyConstraint(['objid'], ['objects.objid'], ),
    sa.PrimaryKeyConstraint('objid', 'classif_date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objectsclassifhisto')
    ### end Alembic commands ###
