"""empty message

Revision ID: 2fff5d2d55e
Revises: 28ee72b54d2
Create Date: 2015-07-29 14:52:44.281250

"""

# revision identifiers, used by Alembic.
revision = "2fff5d2d55e"
down_revision = "28ee72b54d2"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "objectsclassifhisto",
        sa.Column("classif_score", postgresql.DOUBLE_PRECISION(), nullable=True),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objectsclassifhisto", "classif_score")
    ### end Alembic commands ###
