"""empty message

Revision ID: 35177c28cb
Revises: 55f81c16f28
Create Date: 2015-07-15 18:56:46.464374

"""

# revision identifiers, used by Alembic.
revision = "35177c28cb"
down_revision = "55f81c16f28"

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("classiffieldlist", sa.VARCHAR(), nullable=True)
    )
    op.add_column("projects", sa.Column("initclassiflist", sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, "temp_tasks", "users", ["owner_id"], ["id"])
    op.add_column(
        "users", sa.Column("preferences", sa.String(length=2000), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "preferences")
    op.drop_constraint(None, "temp_tasks", type_="foreignkey")
    op.drop_column("projects", "initclassiflist")
    op.drop_column("projects", "classiffieldlist")
    ### end Alembic commands ###
