"""catch-up

Revision ID: 4045b161563b
Revises: dac2d438e6b5
Create Date: 2024-10-13 07:01:57.294074

"""

# revision identifiers, used by Alembic.
revision = "4045b161563b"
down_revision = "dac2d438e6b5"

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "is_phy_image_file", "image_file", ["digest_type", "digest"], unique=False
    )
    op.create_foreign_key(None, "images", "obj_head", ["objid"], ["objid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
