"""empty message

Revision ID: 519060922e3
Revises: 16b84aae414
Create Date: 2015-09-02 06:26:03.513243

"""

# revision identifiers, used by Alembic.
revision = "519060922e3"
down_revision = "16b84aae414"

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "IS_ObjectsOrigID",
        "objects",
        ["projid", "orig_id", "classif_qual", "classif_who"],
        unique=False,
    )
    op.drop_column("objects", "weblink")
    op.add_column(
        "projects", sa.Column("popoverfieldlist", sa.VARCHAR(), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "popoverfieldlist")
    op.add_column(
        "objects",
        sa.Column("weblink", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index("IS_ObjectsOrigID", table_name="objects")
    ### end Alembic commands ###
