"""new report tables

Revision ID: 521c25353fa0
Revises: 8ac7e3c29305
Create Date: 2023-01-15 07:20:30.825711

"""

# revision identifiers, used by Alembic.
revision = "521c25353fa0"
down_revision = "8ac7e3c29305"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects_variables",
        sa.Column("project_id", sa.INTEGER(), nullable=False),
        sa.Column("subsample_coef", sa.VARCHAR(), nullable=True),
        sa.Column("total_water_volume", sa.VARCHAR(), nullable=True),
        sa.Column("individual_volume", sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.projid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.add_column(
        "obj_field",
        sa.Column("acquis_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "obj_field_acquisid_objfid_idx",
        "obj_field",
        ["acquis_id", "objfid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects_variables")
    # ### end Alembic commands ###
