"""new report tables

Revision ID: 521c25353fa0
Revises: 8ac7e3c29305
Create Date: 2023-01-15 07:20:30.825711

"""

# revision identifiers, used by Alembic.
revision = '521c25353fa0'
down_revision = '8ac7e3c29305'

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_variables',
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('subsample_coef', sa.VARCHAR(), nullable=True),
    sa.Column('total_water_volume', sa.VARCHAR(), nullable=True),
    sa.Column('individual_biovolume', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projid'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('taxo_recast',
    sa.Column('collection_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('operation', sa.VARCHAR(length=32), nullable=False),
    sa.Column('transform', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projid'], ),
    sa.PrimaryKeyConstraint('collection_id', 'project_id', 'operation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxo_recast')
    op.drop_table('projects_variables')
    # ### end Alembic commands ###
