"""base tables optimization

Revision ID: 52a9d347f2b2
Revises: 1b1beb672279
Create Date: 2024-02-15 07:45:03.011707

"""

# revision identifiers, used by Alembic.
revision = "52a9d347f2b2"
down_revision = "1b1beb672279"

import sqlalchemy as sa
from alembic import op


# This needs to go after the manual files in manual17feb2024


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IS_AcquisOrigId", table_name="acquisitions")
    op.create_index(
        "is_acquis_sample_orig_id",
        "acquisitions",
        ["acq_sample_id", "orig_id"],
        unique=True,
        postgresql_include=["acquisid"],
    )
    op.drop_index("IS_SamplesProjectOrigId", table_name="samples")
    op.create_index(
        "is_samples_project_orig_id",
        "samples",
        ["projid", "orig_id"],
        unique=True,
        postgresql_include=["sampleid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "is_samples_project_orig_id",
        table_name="samples",
        postgresql_include=sa.text("sampleid"),
    )
    op.create_index(
        "IS_SamplesProjectOrigId", "samples", ["projid", "orig_id"], unique=False
    )
    op.drop_index(
        "is_acquis_sample_orig_id",
        table_name="acquisitions",
        postgresql_include=sa.text("acquisid"),
    )
    op.create_index(
        "IS_AcquisOrigId", "acquisitions", ["acq_sample_id", "orig_id"], unique=False
    )
    # ### end Alembic commands ###
