"""empty message

Revision ID: 5b2908d16916
Revises: 76f5e43ee3d4
Create Date: 2020-05-11 06:44:45.426621

"""

# revision identifiers, used by Alembic.
revision = "5b2908d16916"
down_revision = "76f5e43ee3d4"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "part_projects",
        sa.Column("enable_descent_filter", sa.CHAR(length=1), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("part_projects", "enable_descent_filter")
    # ### end Alembic commands ###
