"""organizations users relation

Revision ID: 5b706c64bae0
Revises: e6dda08ff48b
Create Date: 2025-01-17 14:48:54.137602

"""

# revision identifiers, used by Alembic.
revision = "5b706c64bae0"
down_revision = "e6dda08ff48b"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("orgname", "organizations", ["name"])
    op.drop_column("organizations", "id")
    op.execute(
        "INSERT INTO organizations (name) SELECT DISTINCT organisation FROM users WHERE organisation IS NOT NULL"
    )
    op.create_foreign_key(None, "users", "organizations", ["organisation"], ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint("orgname", "organizations", type_="unique")
    op.add_column(
        "organizations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )

    # ### end Alembic commands ###
