"""partition

Revision ID: 5d49f4994e0c
Revises: acf6f3fcb35c
Create Date: 2026-05-02 06:42:20.254029

"""

# revision identifiers, used by Alembic.
revision = "5d49f4994e0c"
down_revision = "acf6f3fcb35c"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from DB.Object import OBJ_PRJ_OFFSET


def upgrade():
    # Check if there are any objects in the DB
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT count(*) FROM obj_head")).scalar()
    if result > 0:
        raise Exception(
            "There are objects in the database. This migration cannot proceed, you must use renumber.sql instead"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("is_objectsacqclassifqual", table_name="obj_head")
    op.create_index(
        "is_objectsacqclassifqual",
        "obj_head",
        ["acquisid", "objid"],
        unique=True,
        postgresql_include=["classif_qual", "classif_id"],
    )

    op.drop_index("is_obj_head_acquisid_objid", table_name="obj_head")

    op.drop_index("obj_field_acquisid_objfid_idx", table_name="obj_field")
    op.create_index(
        "obj_field_acquisid_objfid_idx",
        "obj_field",
        ["acquis_id", "objfid"],
        unique=True,
        postgresql_include=["n01", "n02", "n03", "n04"],
    )

    op.drop_constraint("acquisitions_sampleid_fkey", "acquisitions", type_="foreignkey")
    op.create_foreign_key(
        None,
        "acquisitions",
        "samples",
        ["acq_sample_id"],
        ["sampleid"],
        onupdate="CASCADE",
    )
    op.drop_constraint("images_objid_fkey", "images", type_="foreignkey")
    op.create_foreign_key(
        None, "images", "obj_head", ["objid"], ["objid"], onupdate="CASCADE"
    )
    op.drop_constraint("obj_head_acquisid_fkey", "obj_head", type_="foreignkey")
    op.create_foreign_key(
        None,
        "obj_head",
        "acquisitions",
        ["acquisid"],
        ["acquisid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "obj_cnn_features_vector_objcnnid_fkey",
        "obj_cnn_features_vector",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "obj_cnn_features_vector",
        "obj_head",
        ["objcnnid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("obj_field_objfid_fkey", "obj_field", type_="foreignkey")
    op.create_foreign_key(
        None,
        "obj_field",
        "obj_head",
        ["objfid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "objectsclassifhisto_objid_fkey", "objectsclassifhisto", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "objectsclassifhisto",
        "obj_head",
        ["objid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("prediction_object_id_fkey", "prediction", type_="foreignkey")
    op.create_foreign_key(
        None,
        "prediction",
        "obj_head",
        ["object_id"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "prediction_histo_object_id_fkey", "prediction_histo", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "prediction_histo",
        "obj_head",
        ["object_id"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("process_processid_fkey", "process", type_="foreignkey")
    op.create_foreign_key(
        None,
        "process",
        "acquisitions",
        ["processid"],
        ["acquisid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )

    # TODO: Why these?
    # op.drop_table("collection_orga_role_w_organization")
    # op.drop_column("projects", "license")
    # op.drop_column("projects", "visible")
    # op.alter_column("users", "type", existing_type=sa.VARCHAR(length=10), nullable=True)
    # op.drop_column("users", "organization")

    op.execute(f"""
CREATE OR REPLACE FUNCTION obj_in_prj(prj_id int)
RETURNS int8range AS $$
  SELECT int8range(
    prj_id * {OBJ_PRJ_OFFSET}::bigint,
    (prj_id + 1) * {OBJ_PRJ_OFFSET}::bigint,
    '[)'
  );
$$ LANGUAGE sql IMMUTABLE;

GRANT EXECUTE ON FUNCTION obj_in_prj(int) TO PUBLIC;
""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "organization", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "users", "type", existing_type=sa.VARCHAR(length=10), nullable=False
    )

    op.execute("DROP FUNCTION IF EXISTS obj_in_prj(int)")

    op.add_column(
        "projects",
        sa.Column("visible", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column(
            "license",
            sa.VARCHAR(length=16),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_constraint("process_processid_fkey", "process", type_="foreignkey")
    op.create_foreign_key(
        "process_processid_fkey",
        "process",
        "acquisitions",
        ["processid"],
        ["acquisid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "prediction_histo_object_id_fkey", "prediction_histo", type_="foreignkey"
    )
    op.create_foreign_key(
        "prediction_histo_object_id_fkey",
        "prediction_histo",
        "obj_head",
        ["object_id"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("prediction_object_id_fkey", "prediction", type_="foreignkey")
    op.create_foreign_key(
        "prediction_object_id_fkey",
        "prediction",
        "obj_head",
        ["object_id"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "objectsclassifhisto_objid_fkey", "objectsclassifhisto", type_="foreignkey"
    )
    op.create_foreign_key(
        "objectsclassifhisto_objid_fkey",
        "objectsclassifhisto",
        "obj_head",
        ["objid"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("obj_head_acquisid_fkey", "obj_head", type_="foreignkey")
    op.create_foreign_key(
        "obj_head_acquisid_fkey",
        "obj_head",
        "acquisitions",
        ["acquisid"],
        ["acquisid"],
        ondelete="CASCADE",
    )

    op.drop_index(
        "is_objectsacqclassifqual",
        table_name="obj_head",
        postgresql_include=["classif_qual", "classif_id"],
    )
    op.create_index(
        "is_objectsacqclassifqual",
        "obj_head",
        ["acquisid", "classif_qual"],
        unique=False,
    )
    op.create_index(
        "is_obj_head_acquisid_objid", "obj_head", ["acquisid", "objid"], unique=False
    )

    op.drop_constraint("obj_field_objfid_fkey", "obj_field", type_="foreignkey")
    op.create_foreign_key(
        "obj_field_objfid_fkey",
        "obj_field",
        "obj_head",
        ["objfid"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "obj_field_acquisid_objfid_idx",
        table_name="obj_field",
        postgresql_include=["n01", "n02", "n03", "n04"],
    )
    op.create_index(
        "obj_field_acquisid_objfid_idx",
        "obj_field",
        ["acquis_id", "objfid"],
        unique=False,
    )
    op.drop_constraint(
        "obj_cnn_features_vector_objcnnid_fkey",
        "obj_cnn_features_vector",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "obj_cnn_features_vector_objcnnid_fkey",
        "obj_cnn_features_vector",
        "obj_head",
        ["objcnnid"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "obj_cnn_features_vector_hv_ivfflat_l2_5k_idx",
        table_name="obj_cnn_features_vector",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 5000},
    )
    op.drop_constraint("images_objid_fkey", "images", type_="foreignkey")
    op.create_foreign_key(
        "images_objid_fkey", "images", "obj_head", ["objid"], ["objid"]
    )
    op.drop_constraint("acquisitions_sampleid_fkey", "acquisitions", type_="foreignkey")
    op.create_foreign_key(
        "acquisitions_sampleid_fkey",
        "acquisitions",
        "samples",
        ["acq_sample_id"],
        ["sampleid"],
    )
    op.create_table(
        "collection_orga_role_w_organization",
        sa.Column("collection_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "organization", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("role", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "dbplyr_004",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_002",
        sa.Column(
            "psampleid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sampleid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_001",
        sa.Column(
            "psampleid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sampleid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_007",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_003",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_006",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_005",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
