"""partition

Revision ID: 5d49f4994e0c
Revises: acf6f3fcb35c
Create Date: 2026-05-02 06:42:20.254029

"""

# revision identifiers, used by Alembic.
revision = "5d49f4994e0c"
down_revision = "acf6f3fcb35c"

import sqlalchemy as sa
from alembic import op

from DB.Object import OBJ_PRJ_OFFSET


def upgrade():
    # Check if there are any objects in the DB
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT count(*) FROM obj_head"))
    if result is not None and result.scalar() > 0:
        raise Exception(
            "There are objects in the database. This migration cannot proceed, you must use renumber.sql instead"
        )

    op.execute("DROP VIEW IF EXISTS objects")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acqid_old_2_new",
        sa.Column("old_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("new_id", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("old_id"),
    )
    op.create_index(
        "acquisid_mapping_idx",
        "acqid_old_2_new",
        ["new_id"],
        unique=False,
        postgresql_include=["old_id"],
    )
    op.create_index(
        "acquisid_mapping_idx2",
        "acqid_old_2_new",
        ["old_id"],
        unique=False,
        postgresql_include=["new_id"],
    )
    op.create_table(
        "objid_old_2_new",
        sa.Column("old_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("new_id", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("old_id"),
    )
    op.create_index(
        "objid_mapping_new_to_old",
        "objid_old_2_new",
        ["new_id"],
        unique=True,
        postgresql_include=["old_id"],
    )
    op.create_index(
        "objid_mapping_old_to_new",
        "objid_old_2_new",
        ["old_id"],
        unique=True,
        postgresql_include=["new_id"],
    )
    op.create_table(
        "samid_old_2_new",
        sa.Column("old_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("new_id", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("old_id"),
    )
    op.drop_index("is_objectsacqclassifqual", table_name="obj_head")
    op.create_index(
        "is_objectsacqclassifqual",
        "obj_head",
        ["acquisid", "objid"],
        unique=True,
        postgresql_include=["classif_qual", "classif_id"],
    )

    op.drop_index("is_obj_head_acquisid_objid", table_name="obj_head")

    op.drop_index("obj_field_acquisid_objfid_idx", table_name="obj_field")
    op.alter_column(
        "obj_field", "acquis_id", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.create_index(
        "obj_field_acquisid_objfid_idx",
        "obj_field",
        ["acquis_id", "objfid"],
        unique=True,
        postgresql_include=["n01", "n02", "n03", "n04"],
    )

    op.drop_constraint("acquisitions_sampleid_fkey", "acquisitions", type_="foreignkey")
    op.alter_column(
        "samples", "sampleid", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.alter_column(
        "acquisitions", "acq_sample_id", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.create_foreign_key(
        None,
        "acquisitions",
        "samples",
        ["acq_sample_id"],
        ["sampleid"],
        onupdate="CASCADE",
    )
    op.drop_constraint("images_objid_fkey", "images", type_="foreignkey")
    op.create_foreign_key(
        None, "images", "obj_head", ["objid"], ["objid"], onupdate="CASCADE"
    )
    op.drop_constraint("obj_head_acquisid_fkey", "obj_head", type_="foreignkey")
    op.alter_column(
        "acquisitions", "acquisid", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.alter_column(
        "obj_head", "acquisid", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.create_foreign_key(
        None,
        "obj_head",
        "acquisitions",
        ["acquisid"],
        ["acquisid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "obj_cnn_features_vector_objcnnid_fkey",
        "obj_cnn_features_vector",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "obj_cnn_features_vector",
        "obj_head",
        ["objcnnid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("obj_field_objfid_fkey", "obj_field", type_="foreignkey")
    op.create_foreign_key(
        None,
        "obj_field",
        "obj_head",
        ["objfid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "objectsclassifhisto_objid_fkey", "objectsclassifhisto", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "objectsclassifhisto",
        "obj_head",
        ["objid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("prediction_object_id_fkey", "prediction", type_="foreignkey")
    op.create_foreign_key(
        None,
        "prediction",
        "obj_head",
        ["object_id"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "prediction_histo_object_id_fkey", "prediction_histo", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "prediction_histo",
        "obj_head",
        ["object_id"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("process_processid_fkey", "process", type_="foreignkey")
    op.alter_column(
        "process", "processid", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.create_foreign_key(
        None,
        "process",
        "acquisitions",
        ["processid"],
        ["acquisid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )

    # TODO: Why these?
    # op.drop_table("collection_orga_role_w_organization")
    # op.drop_column("projects", "license")
    # op.drop_column("projects", "visible")
    # op.alter_column("users", "type", existing_type=sa.VARCHAR(length=10), nullable=True)
    # op.drop_column("users", "organization")

    op.execute(f"""
CREATE OR REPLACE FUNCTION obj_in_prj(prj_id int)
RETURNS int8range AS $$
  SELECT int8range(
    prj_id * {OBJ_PRJ_OFFSET}::bigint,
    (prj_id + 1) * {OBJ_PRJ_OFFSET}::bigint,
    '[)'
  );
$$ LANGUAGE sql IMMUTABLE;

GRANT EXECUTE ON FUNCTION obj_in_prj(int) TO PUBLIC;

CREATE OR REPLACE VIEW objects AS
SELECT prj.projid,
       sam.sampleid,
       obh.objid,
       obh.latitude,
       obh.longitude,
       obh.objdate,
       obh.objtime,
       obh.depth_min,
       obh.depth_max,
       obh.classif_id,
       obh.classif_qual,
       obh.classif_who,
       CASE WHEN obh.classif_qual IN ('V', 'D') THEN obh.classif_date END AS classif_when,
       obh.classif_score                                                  AS classif_auto_score,
       CASE WHEN obh.classif_qual = 'P' THEN obh.classif_date END         AS classif_auto_when,
       CASE WHEN obh.classif_qual = 'P' THEN obh.classif_id END           AS classif_auto_id,
       NULL::integer                                                      AS classif_crossvalidation_id,
       obh.complement_info,
       NULL::double precision                                             AS similarity,
       obh.sunpos,
       HASHTEXT(obh.orig_id)                                              AS random_value,
       obh.acquisid,
       obh.object_link,
       obh.orig_id,
       obh.acquisid                                                       AS processid,
       ofi.*
    FROM projects prj
    JOIN samples sam ON sam.projid = prj.projid
    JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid
    JOIN obj_head obh ON obh.acquisid = acq.acquisid AND obh.objid <@ obj_in_prj(prj.projid)
    LEFT JOIN obj_field ofi ON obh.objid = ofi.objfid
""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise "No way back"
