"""partition

Revision ID: 5d49f4994e0c
Revises: acf6f3fcb35c
Create Date: 2026-05-02 06:42:20.254029

"""

# revision identifiers, used by Alembic.
revision = "5d49f4994e0c"
down_revision = "acf6f3fcb35c"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from DB.Object import OBJ_PRJ_OFFSET


def upgrade():
    # Check if there are any objects in the DB
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT count(*) FROM obj_head"))
    if result is not None and result.scalar() > 0:
        raise Exception(
            "There are objects in the database. This migration cannot proceed, you must use renumber.sql instead"
        )

    op.execute("DROP VIEW IF EXISTS objects")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("is_objectsacqclassifqual", table_name="obj_head")
    op.create_index(
        "is_objectsacqclassifqual",
        "obj_head",
        ["acquisid", "objid"],
        unique=True,
        postgresql_include=["classif_qual", "classif_id"],
    )

    op.drop_index("is_obj_head_acquisid_objid", table_name="obj_head")

    op.drop_index("obj_field_acquisid_objfid_idx", table_name="obj_field")
    op.alter_column(
        "obj_field", "acquis_id", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.create_index(
        "obj_field_acquisid_objfid_idx",
        "obj_field",
        ["acquis_id", "objfid"],
        unique=True,
        postgresql_include=["n01", "n02", "n03", "n04"],
    )

    op.drop_constraint("acquisitions_sampleid_fkey", "acquisitions", type_="foreignkey")
    op.alter_column(
        "samples", "sampleid", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.alter_column(
        "acquisitions", "acq_sample_id", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.create_foreign_key(
        None,
        "acquisitions",
        "samples",
        ["acq_sample_id"],
        ["sampleid"],
        onupdate="CASCADE",
    )
    op.drop_constraint("images_objid_fkey", "images", type_="foreignkey")
    op.create_foreign_key(
        None, "images", "obj_head", ["objid"], ["objid"], onupdate="CASCADE"
    )
    op.drop_constraint("obj_head_acquisid_fkey", "obj_head", type_="foreignkey")
    op.alter_column(
        "acquisitions", "acquisid", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.alter_column(
        "obj_head", "acquisid", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.create_foreign_key(
        None,
        "obj_head",
        "acquisitions",
        ["acquisid"],
        ["acquisid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "obj_cnn_features_vector_objcnnid_fkey",
        "obj_cnn_features_vector",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "obj_cnn_features_vector",
        "obj_head",
        ["objcnnid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("obj_field_objfid_fkey", "obj_field", type_="foreignkey")
    op.create_foreign_key(
        None,
        "obj_field",
        "obj_head",
        ["objfid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "objectsclassifhisto_objid_fkey", "objectsclassifhisto", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "objectsclassifhisto",
        "obj_head",
        ["objid"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("prediction_object_id_fkey", "prediction", type_="foreignkey")
    op.create_foreign_key(
        None,
        "prediction",
        "obj_head",
        ["object_id"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "prediction_histo_object_id_fkey", "prediction_histo", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "prediction_histo",
        "obj_head",
        ["object_id"],
        ["objid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("process_processid_fkey", "process", type_="foreignkey")
    op.alter_column(
        "process", "processid", existing_type=sa.INTEGER(), type_=sa.BIGINT()
    )
    op.create_foreign_key(
        None,
        "process",
        "acquisitions",
        ["processid"],
        ["acquisid"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )

    # TODO: Why these?
    # op.drop_table("collection_orga_role_w_organization")
    # op.drop_column("projects", "license")
    # op.drop_column("projects", "visible")
    # op.alter_column("users", "type", existing_type=sa.VARCHAR(length=10), nullable=True)
    # op.drop_column("users", "organization")

    op.execute(f"""
CREATE OR REPLACE FUNCTION obj_in_prj(prj_id int)
RETURNS int8range AS $$
  SELECT int8range(
    prj_id * {OBJ_PRJ_OFFSET}::bigint,
    (prj_id + 1) * {OBJ_PRJ_OFFSET}::bigint,
    '[)'
  );
$$ LANGUAGE sql IMMUTABLE;

GRANT EXECUTE ON FUNCTION obj_in_prj(int) TO PUBLIC;

CREATE OR REPLACE VIEW objects AS
SELECT prj.projid,
       sam.sampleid,
       obh.objid,
       obh.latitude,
       obh.longitude,
       obh.objdate,
       obh.objtime,
       obh.depth_min,
       obh.depth_max,
       obh.classif_id,
       obh.classif_qual,
       obh.classif_who,
       CASE WHEN obh.classif_qual IN ('V', 'D') THEN obh.classif_date END AS classif_when,
       obh.classif_score                                                  AS classif_auto_score,
       CASE WHEN obh.classif_qual = 'P' THEN obh.classif_date END         AS classif_auto_when,
       CASE WHEN obh.classif_qual = 'P' THEN obh.classif_id END           AS classif_auto_id,
       NULL::integer                                                      AS classif_crossvalidation_id,
       obh.complement_info,
       NULL::double precision                                             AS similarity,
       obh.sunpos,
       HASHTEXT(obh.orig_id)                                              AS random_value,
       obh.acquisid,
       obh.object_link,
       obh.orig_id,
       obh.acquisid                                                       AS processid,
       ofi.*
    FROM projects prj
    JOIN samples sam ON sam.projid = prj.projid
    JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid
    JOIN obj_head obh ON obh.acquisid = acq.acquisid AND obh.objid <@ obj_in_prj(prj.projid)
    LEFT JOIN obj_field ofi ON obh.objid = ofi.objfid
""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "organization", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "users", "type", existing_type=sa.VARCHAR(length=10), nullable=False
    )

    op.execute("DROP FUNCTION IF EXISTS obj_in_prj(int)")

    op.execute("""
    create or replace view objects as 
       select sam.projid, sam.sampleid, obh.objid, obh.latitude, obh.longitude,
              obh.objdate, obh.objtime, obh.depth_min, obh.depth_max,
              obh.classif_id, obh.classif_qual, obh.classif_who, 
              CASE WHEN obh.classif_qual in ('V', 'D') THEN obh.classif_date END AS classif_when,
              obh.classif_score AS classif_auto_score,
              CASE WHEN obh.classif_qual = 'P' THEN obh.classif_date END AS classif_auto_when,
              CASE WHEN obh.classif_qual = 'P' THEN obh.classif_id END AS classif_auto_id,
              NULL::integer AS classif_crossvalidation_id,
              obh.complement_info,
              NULL::double precision AS similarity,
              obh.sunpos,
              HASHTEXT(obh.orig_id) AS random_value,
              obh.acquisid, obh.object_link, obh.orig_id, obh.acquisid AS processid, 
              ofi.*
         from obj_head obh
         join acquisitions acq on obh.acquisid = acq.acquisid
         join samples sam on acq.acq_sample_id = sam.sampleid 
         left join obj_field ofi on obh.objid = ofi.objfid;
    grant select on objects to zoo;
    grant select on objects to readerole;
""")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "license",
            sa.VARCHAR(length=16),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_constraint("process_processid_fkey", "process", type_="foreignkey")
    op.alter_column(
        "process", "processid", existing_type=sa.BIGINT(), type_=sa.INTEGER()
    )
    op.create_foreign_key(
        "process_processid_fkey",
        "process",
        "acquisitions",
        ["processid"],
        ["acquisid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "prediction_histo_object_id_fkey", "prediction_histo", type_="foreignkey"
    )
    op.create_foreign_key(
        "prediction_histo_object_id_fkey",
        "prediction_histo",
        "obj_head",
        ["object_id"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("prediction_object_id_fkey", "prediction", type_="foreignkey")
    op.create_foreign_key(
        "prediction_object_id_fkey",
        "prediction",
        "obj_head",
        ["object_id"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "objectsclassifhisto_objid_fkey", "objectsclassifhisto", type_="foreignkey"
    )
    op.create_foreign_key(
        "objectsclassifhisto_objid_fkey",
        "objectsclassifhisto",
        "obj_head",
        ["objid"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("obj_head_acquisid_fkey", "obj_head", type_="foreignkey")
    op.alter_column(
        "acquisitions", "acquisid", existing_type=sa.BIGINT(), type_=sa.INTEGER()
    )
    op.alter_column(
        "obj_head", "acquisid", existing_type=sa.BIGINT(), type_=sa.INTEGER()
    )
    op.create_foreign_key(
        "obj_head_acquisid_fkey",
        "obj_head",
        "acquisitions",
        ["acquisid"],
        ["acquisid"],
        ondelete="CASCADE",
    )

    op.drop_index(
        "is_objectsacqclassifqual",
        table_name="obj_head",
        postgresql_include=["classif_qual", "classif_id"],
    )
    op.create_index(
        "is_objectsacqclassifqual",
        "obj_head",
        ["acquisid", "classif_qual"],
        unique=False,
    )
    op.create_index(
        "is_obj_head_acquisid_objid", "obj_head", ["acquisid", "objid"], unique=False
    )

    op.drop_constraint("obj_field_objfid_fkey", "obj_field", type_="foreignkey")
    op.create_foreign_key(
        "obj_field_objfid_fkey",
        "obj_field",
        "obj_head",
        ["objfid"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "obj_field_acquisid_objfid_idx",
        table_name="obj_field",
        postgresql_include=["n01", "n02", "n03", "n04"],
    )
    op.alter_column(
        "obj_field", "acquis_id", existing_type=sa.BIGINT(), type_=sa.INTEGER()
    )
    op.create_index(
        "obj_field_acquisid_objfid_idx",
        "obj_field",
        ["acquis_id", "objfid"],
        unique=False,
    )
    op.drop_constraint(
        "obj_cnn_features_vector_objcnnid_fkey",
        "obj_cnn_features_vector",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "obj_cnn_features_vector_objcnnid_fkey",
        "obj_cnn_features_vector",
        "obj_head",
        ["objcnnid"],
        ["objid"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "obj_cnn_features_vector_hv_ivfflat_l2_5k_idx",
        table_name="obj_cnn_features_vector",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 5000},
    )
    op.drop_constraint("images_objid_fkey", "images", type_="foreignkey")
    op.create_foreign_key(
        "images_objid_fkey", "images", "obj_head", ["objid"], ["objid"]
    )
    op.drop_constraint("acquisitions_sampleid_fkey", "acquisitions", type_="foreignkey")
    op.alter_column(
        "acquisitions", "acq_sample_id", existing_type=sa.BIGINT(), type_=sa.INTEGER()
    )
    op.alter_column(
        "samples", "sampleid", existing_type=sa.BIGINT(), type_=sa.INTEGER()
    )
    op.create_foreign_key(
        "acquisitions_sampleid_fkey",
        "acquisitions",
        "samples",
        ["acq_sample_id"],
        ["sampleid"],
    )
    op.create_table(
        "collection_orga_role_w_organization",
        sa.Column("collection_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "organization", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("role", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "dbplyr_004",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_002",
        sa.Column(
            "psampleid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sampleid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_001",
        sa.Column(
            "psampleid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sampleid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_007",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_003",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_006",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "dbplyr_005",
        sa.Column(
            "pprojid",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("project", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("project_short", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "use",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
