"""instruments

Revision ID: 8ac7e3c29305
Revises: 088904e6b78e
Create Date: 2022-03-02 16:15:31.664935

"""

from data.Instruments import DEFAULT_INSTRUMENTS

# revision identifiers, used by Alembic.
revision = "8ac7e3c29305"
down_revision = "088904e6b78e"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tbl = op.create_table(
        "instrument",
        sa.Column("instrument_id", sa.VARCHAR(length=32), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("bodc_url", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("instrument_id"),
    )
    instrs = [
        {"instrument_id": ins, "name": nam, "bodc_url": url}
        for ins, nam, url in DEFAULT_INSTRUMENTS
    ]
    op.bulk_insert(tbl, instrs)
    default = DEFAULT_INSTRUMENTS[-1][0]
    op.add_column(
        "projects",
        sa.Column(
            "instrument_id",
            sa.VARCHAR(length=32),
            nullable=False,
            server_default=default,
        ),
    )
    op.alter_column("projects", "instrument_id", server_default=None)
    op.create_foreign_key(
        None, "projects", "instrument", ["instrument_id"], ["instrument_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("projects_instrument_id_fkey", "projects", type_="foreignkey")
    op.drop_column("projects", "instrument_id")
    op.drop_table("instrument")
    # ### end Alembic commands ###
