"""new indexes

Revision ID: 9bf6b31796a2
Revises: ca50a945b178
Create Date: 2026-04-09 12:53:31.409449

"""

# revision identifiers, used by Alembic.
revision = "9bf6b31796a2"
down_revision = "ca50a945b178"

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "is_acquis_sample",
        "acquisitions",
        ["acq_sample_id"],
        unique=False,
        postgresql_include=["acquisid"],
    )
    op.create_index(
        "is_samples_project",
        "samples",
        ["projid"],
        unique=False,
        postgresql_include=["sampleid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("is_samples_project", table_name="samples")
    op.drop_index("is_acquis_sample", table_name="acquisitions")
    # ### end Alembic commands ###
