"""organization_id

Revision ID: 9f8174c268da
Revises: e6dda08ff48b
Create Date: 2025-03-12 15:08:22.505508

"""

# revision identifiers, used by Alembic.
revision = "9f8174c268da"
down_revision = "e6dda08ff48b"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection_orga_role",
        sa.Column("organization_id", sa.INTEGER()),
    )
    op.create_foreign_key(
        "collection_organization_fkey",
        "collection_orga_role",
        "organizations",
        ["organization_id"],
        ["id"],
    )

    op.add_column("users", sa.Column("organization_id", sa.INTEGER()))
    op.execute(
        "INSERT INTO organizations (name) SELECT DISTINCT organisation FROM collection_orga_role WHERE organisation IS NOT NULL AND NOT EXISTS (SELECT organizations.id FROM organizations  WHERE organisation=organizations.name);"
    )
    op.execute(
        "UPDATE collection_orga_role SET organization_id=subquery.id FROM(SELECT id,name FROM organizations) AS subquery WHERE subquery.name LIKE collection_orga_role.organisation;"
    )
    op.execute(
        "ALTER TABLE collection_orga_role RENAME COLUMN organisation TO organization;"
    )
    op.execute(
        "UPDATE users SET organization_id=subquery.id FROM(SELECT id,name FROM organizations) AS subquery WHERE subquery.name LIKE users.organisation;"
    )
    op.execute("ALTER TABLE users RENAME COLUMN organisation TO organization;")
    op.execute(
        "ALTER TABLE collection_orga_role ALTER COLUMN organization_id SET NOT NULL;"
    )
    op.drop_constraint("users_organisation", "users", type_="foreignkey")
    op.create_foreign_key(
        "user_organization_fkey", "users", "organizations", ["organization_id"], ["id"]
    )
    # op.drop_column("collection_orga_role", "organisation")
    # op.drop_column("users", "organisation")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "organisation", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint("user_organization_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        "users_organisation", "users", "organizations", ["organisation"], ["name"]
    )
    op.alter_column(
        "users", "type", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.drop_column("users", "organization_id")

    op.add_column(
        "collection_orga_role",
        sa.Column("organisation", sa.VARCHAR(length=255), nullable=False),
    )
    op.drop_constraint(
        "collection_organization_fkey", "collection_orga_role", type_="foreignkey"
    )
    op.drop_column("collection_orga_role", "organization_id")

    # ### end Alembic commands ###
