"""empty message

Revision ID: a1bb3311036c
Revises: e1c32fc967e8
Create Date: 2017-12-15 17:26:59.530614

"""

# revision identifiers, used by Alembic.
revision = "a1bb3311036c"
down_revision = "e1c32fc967e8"

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', sa.Column('preferences', sa.String(length=40000), nullable=True))
    # requis par le fait qu'on stocke un settings par projet dans la limite de 50
    op.execute("ALTER table users alter column preferences type varchar(40000)")
    # ### end Alembic commands ###


def downgrade():
    None
