"""New table to keep history of mass taxo change

Revision ID: a4c0d0c48e5a
Revises: 00601700d281
Create Date: 2021-09-07 11:25:18.214752

"""

# revision identifiers, used by Alembic.
revision = 'a4c0d0c48e5a'
down_revision = '00601700d281'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxo_change_log',
    sa.Column('from_id', sa.INTEGER(), nullable=False),
    sa.Column('to_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('why', sa.VARCHAR(length=1), nullable=False),
    sa.Column('impacted', sa.INTEGER(), nullable=False),
    sa.Column('occurred_on', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['taxonomy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_id', 'to_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxo_change_log')
    # ### end Alembic commands ###
