"""similarity search

Revision ID: a9dd3c62b7b0
Revises: 0a3132f436fb
Create Date: 2024-02-19 16:53:45.397975

"""

# revision identifiers, used by Alembic.
revision = "a9dd3c62b7b0"
down_revision = "0a3132f436fb"

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector  # type:ignore


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "obj_cnn_features_vector",
        sa.Column("objcnnid", sa.BIGINT(), nullable=False),
        sa.Column("features", Vector(dim=50), nullable=True),
        sa.ForeignKeyConstraint(["objcnnid"], ["obj_head.objid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("objcnnid"),
    )
    op.execute(
        """
        INSERT INTO obj_cnn_features_vector (objcnnid, features)
        SELECT objcnnid, ARRAY[cnn01, cnn02, cnn03, cnn04, cnn05, cnn06, cnn07, cnn08, cnn09, cnn10, 
        cnn11, cnn12, cnn13, cnn14, cnn15, cnn16, cnn17, cnn18, cnn19, cnn20, 
        cnn21, cnn22, cnn23, cnn24, cnn25, cnn26, cnn27, cnn28, cnn29, cnn30, 
        cnn31, cnn32, cnn33, cnn34, cnn35, cnn36, cnn37, cnn38, cnn39, cnn40, 
        cnn41, cnn42, cnn43, cnn44, cnn45, cnn46, cnn47, cnn48, cnn49, cnn50]::vector 
        FROM obj_cnn_features
    """
    )
    op.execute(
        """
        GRANT SELECT ON obj_cnn_features_vector TO readerole
        """
    )
    op.drop_table("obj_cnn_features")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("obj_cnn_features_vector")
    # ### end Alembic commands ###
