"""similarity search

Revision ID: a9dd3c62b7b0
Revises: 52a9d347f2b2
Create Date: 2024-02-19 16:53:45.397975

"""

# revision identifiers, used by Alembic.
revision = "a9dd3c62b7b0"
down_revision = "52a9d347f2b2"

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector  # type:ignore


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "obj_cnn_features_vector",
        sa.Column("objcnnid", sa.BIGINT(), nullable=False),
        sa.Column("features", Vector(dim=50), nullable=True),
        sa.ForeignKeyConstraint(["objcnnid"], ["obj_head.objid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("objcnnid"),
    )
    op.execute(
        """
        INSERT INTO obj_cnn_features_vector (objcnnid, features)
        SELECT objcnnid, ARRAY[cnn01, cnn02, cnn03, cnn04, cnn05, cnn06, cnn07, cnn08, cnn09, cnn10, 
        cnn11, cnn12, cnn13, cnn14, cnn15, cnn16, cnn17, cnn18, cnn19, cnn20, 
        cnn21, cnn22, cnn23, cnn24, cnn25, cnn26, cnn27, cnn28, cnn29, cnn30, 
        cnn31, cnn32, cnn33, cnn34, cnn35, cnn36, cnn37, cnn38, cnn39, cnn40, 
        cnn41, cnn42, cnn43, cnn44, cnn45, cnn46, cnn47, cnn48, cnn49, cnn50]::vector 
        FROM obj_cnn_features
    """
    )
    op.drop_table("obj_cnn_features")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "obj_cnn_features",
        sa.Column("objcnnid", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("cnn01", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn02", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn03", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn04", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn05", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn06", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn07", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn08", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn09", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn10", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn11", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn12", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn13", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn14", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn15", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn16", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn17", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn18", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn19", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn20", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn21", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn22", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn23", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn24", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn25", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn26", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn27", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn28", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn29", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn30", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn31", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn32", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn33", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn34", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn35", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn36", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn37", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn38", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn39", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn40", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn41", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn42", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn43", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn44", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn45", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn46", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn47", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn48", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn49", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column("cnn50", sa.REAL(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["objcnnid"],
            ["obj_head.objid"],
            name="obj_cnn_features_objcnnid_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("objcnnid", name="obj_cnn_features_pkey"),
    )
    op.drop_table("obj_cnn_features_vector")
    # ### end Alembic commands ###


