"""empty message

Revision ID: a9f4e64ac4
Revises: 2fff5d2d55e
Create Date: 2015-08-03 11:40:25.640625

"""

# revision identifiers, used by Alembic.
revision = "a9f4e64ac4"
down_revision = "2fff5d2d55e"

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("IS_TaxonomyName", table_name="taxonomy")
    op.create_index(
        "IS_TaxonomyNameLow", "taxonomy", [sa.text("lower(name)")], unique=False
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index("IS_TaxonomyName", "taxonomy", ["name"], unique=False)
    ### end Alembic commands ###
