"""Project license added

Revision ID: af87eb95cafc
Revises: 5d74c0d91171
Create Date: 2020-10-23 12:36:38.789296

"""

# revision identifiers, used by Alembic.
revision = 'af87eb95cafc'
down_revision = '1be2ade9f03b'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('license', sa.VARCHAR(length=16),
                                        nullable=False, server_default='Copyright'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'license')
    # ### end Alembic commands ###
