"""empty message

Revision ID: beaa3e8e4033
Revises: a4c0d0c48e5a
Create Date: 2021-09-30 14:43:35.207397

"""

# revision identifiers, used by Alembic.
revision = "beaa3e8e4033"
down_revision = "a4c0d0c48e5a"

move_projid_to_description = """
BEGIN;
UPDATE projects
   SET description = projtype;
COMMIT;
"""

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.VARCHAR(), nullable=True))
    op.execute(move_projid_to_description)
    op.drop_column("projects", "projtype")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "projtype", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("projects", "description")
    # ### end Alembic commands ###
