"""Project License

Revision ID: c30b923293e9
Revises: 6f57c8aa715d
Create Date: 2021-01-19 11:32:19.464872

"""

# revision identifiers, used by Alembic.
revision = "c30b923293e9"
down_revision = "6f57c8aa715d"

import sqlalchemy as sa
from alembic import op

restore_default = """
    UPDATE projects
       SET license = ''
     WHERE license = 'Copyright'
"""


def upgrade():
    # Bad idea to put a default value not allowing us to know if a choice was ever made
    op.execute(restore_default)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "license",
        existing_type=sa.VARCHAR(length=16),
        nullable=False,
        server_default=sa.text("''"),
        existing_server_default=sa.text("'Copyright'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "license",
        existing_type=sa.VARCHAR(length=16),
        nullable=False,
        server_default=sa.text("'Copyright'::character varying"),
        existing_server_default=sa.text(""),
    )
    # ### end Alembic commands ###
