"""Production DB (as of date below) alignment

Revision ID: c593af18f13a
Revises: 5d49f4994e0c
Create Date: 2026-06-27 10:39:06.814970

"""

# revision identifiers, used by Alembic.
revision = "c593af18f13a"
down_revision = "5d49f4994e0c"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_orga_role_w_organization")
    op.drop_column("projects", "visible")
    op.drop_column("projects", "license")
    op.drop_column("users", "organization")
    op.execute(f"""
    CREATE OR REPLACE VIEW objects AS
    SELECT prj.projid,
           sam.sampleid,
           obh.objid,
           obh.latitude,
           obh.longitude,
           obh.objdate,
           obh.objtime,
           obh.depth_min,
           obh.depth_max,
           obh.classif_id,
           obh.classif_qual,
           obh.classif_who,
           CASE WHEN obh.classif_qual IN ('V', 'D') THEN obh.classif_date END AS classif_when,
           obh.classif_score                                                  AS classif_auto_score,
           CASE WHEN obh.classif_qual = 'P' THEN obh.classif_date END         AS classif_auto_when,
           CASE WHEN obh.classif_qual = 'P' THEN obh.classif_id END           AS classif_auto_id,
           NULL::integer                                                      AS classif_crossvalidation_id,
           obh.complement_info,
           NULL::double precision                                             AS similarity,
           obh.sunpos,
           HASHTEXT(obh.orig_id)                                              AS random_value,
           obh.acquisid,
           obh.object_link,
           obh.orig_id,
           obh.acquisid                                                       AS processid,
           ofi.*
        FROM projects prj
        JOIN samples sam ON sam.projid = prj.projid
        JOIN acquisitions acq ON acq.acq_sample_id = sam.sampleid AND acq.acquisid <@ acq_in_prj(prj.projid)
        JOIN obj_head obh ON obh.acquisid = acq.acquisid AND obh.objid <@ obj_in_prj(prj.projid)
        LEFT JOIN obj_field ofi ON obh.objid = ofi.objfid
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "organization", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "license",
            sa.VARCHAR(length=16),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "projects",
        sa.Column("visible", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "collection_orga_role_w_organization",
        sa.Column("collection_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "organization", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("role", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
