"""taxo_recast column operation length

Revision ID: ca50a945b178
Revises: 287303b6d65c
Create Date: 2026-03-09 15:01:18.993495

"""

# revision identifiers, used by Alembic.
revision = "ca50a945b178"
down_revision = "287303b6d65c"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("projects", "license")
    # op.drop_column("projects", "visible")
    op.create_foreign_key(
        None, "taxo_recast", "projects", ["project_id"], ["projid"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "taxo_recast", "collection", ["collection_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("taxo_recast", "operation", existing_type=sa.VARCHAR(length=32))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("taxo_recast", "operation", existing_type=sa.VARCHAR(length=16))
    op.drop_constraint(None, "taxo_recast", type_="foreignkey")
    op.drop_constraint(None, "taxo_recast", type_="foreignkey")
    # ### end Alembic commands ###
