"""empty message

Revision ID: caae89f1fbfb
Revises: 6e16b3a1d05d
Create Date: 2017-06-18 19:27:33.056176

"""

# revision identifiers, used by Alembic.
revision = 'caae89f1fbfb'
down_revision = '6e16b3a1d05d'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_projects', sa.Column('oldestsampledate', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('part_projects', sa.Column('public_partexport_deferral_month', sa.INTEGER(), nullable=True))
    op.add_column('part_projects', sa.Column('public_visibility_deferral_month', sa.INTEGER(), nullable=True))
    op.add_column('part_projects', sa.Column('public_zooexport_deferral_month', sa.INTEGER(), nullable=True))
    op.add_column('part_samples', sa.Column('imp_descent_filtered_row', sa.INTEGER(), nullable=True))
    op.add_column('part_samples', sa.Column('imp_removed_empty_slice', sa.INTEGER(), nullable=True))
    op.add_column('part_samples', sa.Column('proc_process_ratio', sa.INTEGER(), nullable=True))

    op.execute("INSERT into  roles(name) select 'Particle module project creator' where not exists(select 1 from roles where name='Particle module project creator')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part_samples', 'proc_process_ratio')
    op.drop_column('part_samples', 'imp_removed_empty_slice')
    op.drop_column('part_samples', 'imp_descent_filtered_row')
    op.drop_column('part_projects', 'public_zooexport_deferral_month')
    op.drop_column('part_projects', 'public_visibility_deferral_month')
    op.drop_column('part_projects', 'public_partexport_deferral_month')
    op.drop_column('part_projects', 'oldestsampledate')
    # ### end Alembic commands ###
