"""Redundant columns in obj_head

Revision ID: da78c15a7c21
Revises: a74a857fe352
Create Date: 2021-01-27 11:45:25.507105

"""

# revision identifiers, used by Alembic.
from db_upg.versions.a74a857fe352_no_dup_fk_in_objects import OBJECTS_DDL_a74a857fe352  # type:ignore

revision = 'da78c15a7c21'
down_revision = 'a74a857fe352'

from alembic import op
import sqlalchemy as sa

# imgrank is sometimes duplicate for a same object, dedup.
dedup_ranks = """
create temp table img_issues
as select img.imgid, img.objid, img.imgrank, null::integer as nextrank
from images img
 where exists(select 1 from images img2 where 
              img2.objid=img.objid 
              and img2.imgrank=img.imgrank 
              and img2.imgid != img.imgid);

update img_issues imi
   set nextrank = imgrank + (select count(*) 
                    from images img2 
                   where img2.objid = imi.objid
                     and img2.imgrank <= imi.imgrank
                     and img2.imgid < imi.imgid);

update images img
   set imgrank = nextrank
  from img_issues imi
 where imi.imgid = img.imgid
   and imi.nextrank != imi.imgrank;
"""


def upgrade():
    op.execute('drop view objects')
    op.execute(dedup_ranks)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IS_ImagesObjects', table_name='images')
    op.create_index('is_imageobjrank', 'images', ['objid', 'imgrank'], unique=True)
    # op.drop_constraint('obj_head_acquisid_fkey', 'obj_head', type_='foreignkey')
    # op.create_foreign_key(None, 'obj_head', 'acquisitions', ['acquisid'], ['acquisid'])
    op.drop_column('obj_head', 'img0id')
    op.drop_column('obj_head', 'imgcount')
    # ### end Alembic commands ###
    op.execute(OBJECTS_DDL_a74a857fe352)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obj_head', sa.Column('imgcount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('obj_head', sa.Column('img0id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_index('is_imageobjrank', table_name='images')
    op.create_index('IS_ImagesObjects', 'images', ['objid'], unique=False)
    # ### end Alembic commands ###
