"""empty message

Revision ID: e1c32fc967e8
Revises: caae89f1fbfb
Create Date: 2017-11-06 12:00:19.239108

"""

# revision identifiers, used by Alembic.
revision = 'e1c32fc967e8'
down_revision = 'caae89f1fbfb'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_taxo_stat',
    sa.Column('projid', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nbr', sa.INTEGER(), nullable=True),
    sa.Column('nbr_v', sa.INTEGER(), nullable=True),
    sa.Column('nbr_d', sa.INTEGER(), nullable=True),
    sa.Column('nbr_p', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['projid'], ['projects.projid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('projid', 'id')
    )
    op.create_table('obj_cnn_features',
    sa.Column('objcnnid', sa.BIGINT(), nullable=False),
    sa.Column('cnn01', sa.REAL(), nullable=True),
    sa.Column('cnn02', sa.REAL(), nullable=True),
    sa.Column('cnn03', sa.REAL(), nullable=True),
    sa.Column('cnn04', sa.REAL(), nullable=True),
    sa.Column('cnn05', sa.REAL(), nullable=True),
    sa.Column('cnn06', sa.REAL(), nullable=True),
    sa.Column('cnn07', sa.REAL(), nullable=True),
    sa.Column('cnn08', sa.REAL(), nullable=True),
    sa.Column('cnn09', sa.REAL(), nullable=True),
    sa.Column('cnn10', sa.REAL(), nullable=True),
    sa.Column('cnn11', sa.REAL(), nullable=True),
    sa.Column('cnn12', sa.REAL(), nullable=True),
    sa.Column('cnn13', sa.REAL(), nullable=True),
    sa.Column('cnn14', sa.REAL(), nullable=True),
    sa.Column('cnn15', sa.REAL(), nullable=True),
    sa.Column('cnn16', sa.REAL(), nullable=True),
    sa.Column('cnn17', sa.REAL(), nullable=True),
    sa.Column('cnn18', sa.REAL(), nullable=True),
    sa.Column('cnn19', sa.REAL(), nullable=True),
    sa.Column('cnn20', sa.REAL(), nullable=True),
    sa.Column('cnn21', sa.REAL(), nullable=True),
    sa.Column('cnn22', sa.REAL(), nullable=True),
    sa.Column('cnn23', sa.REAL(), nullable=True),
    sa.Column('cnn24', sa.REAL(), nullable=True),
    sa.Column('cnn25', sa.REAL(), nullable=True),
    sa.Column('cnn26', sa.REAL(), nullable=True),
    sa.Column('cnn27', sa.REAL(), nullable=True),
    sa.Column('cnn28', sa.REAL(), nullable=True),
    sa.Column('cnn29', sa.REAL(), nullable=True),
    sa.Column('cnn30', sa.REAL(), nullable=True),
    sa.Column('cnn31', sa.REAL(), nullable=True),
    sa.Column('cnn32', sa.REAL(), nullable=True),
    sa.Column('cnn33', sa.REAL(), nullable=True),
    sa.Column('cnn34', sa.REAL(), nullable=True),
    sa.Column('cnn35', sa.REAL(), nullable=True),
    sa.Column('cnn36', sa.REAL(), nullable=True),
    sa.Column('cnn37', sa.REAL(), nullable=True),
    sa.Column('cnn38', sa.REAL(), nullable=True),
    sa.Column('cnn39', sa.REAL(), nullable=True),
    sa.Column('cnn40', sa.REAL(), nullable=True),
    sa.Column('cnn41', sa.REAL(), nullable=True),
    sa.Column('cnn42', sa.REAL(), nullable=True),
    sa.Column('cnn43', sa.REAL(), nullable=True),
    sa.Column('cnn44', sa.REAL(), nullable=True),
    sa.Column('cnn45', sa.REAL(), nullable=True),
    sa.Column('cnn46', sa.REAL(), nullable=True),
    sa.Column('cnn47', sa.REAL(), nullable=True),
    sa.Column('cnn48', sa.REAL(), nullable=True),
    sa.Column('cnn49', sa.REAL(), nullable=True),
    sa.Column('cnn50', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['objcnnid'], ['obj_head.objid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('objcnnid')
    )
    op.add_column('projects', sa.Column('cnn_network_id', sa.VARCHAR(length=50), nullable=True))
    op.add_column('projects', sa.Column('rf_models_used', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'rf_models_used')
    op.drop_column('projects', 'cnn_network_id')
    op.drop_table('obj_cnn_features')
    op.drop_table('projects_taxo_stat')
    # ### end Alembic commands ###
