"""project formulae jsonb

Revision ID: e68bf28d2613
Revises: 5d49f4994e0c
Create Date: 2026-07-23 13:47:28.639808

"""

# revision identifiers, used by Alembic.
revision = "e68bf28d2613"
down_revision = "5d49f4994e0c"

import json

import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.dialects import postgresql

from BO.Project import _formulae_str_to_dict


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Legacy string column kept, renamed, as a temporary backup.
    op.alter_column("projects", "formulae", new_column_name="formulae_old")
    op.add_column(
        "projects",
        sa.Column("formulae", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###

    # The row-by-row backfill below needs a live connection to read/write actual
    # data, so it cannot run in `alembic upgrade --sql` (offline/schema-generation)
    # mode -- skip it there. Harmless: SQL-generation is used to rebuild an empty
    # schema (e.g. for QA/upgrade_prod.sql), where there is no legacy data to convert.
    if context.is_offline_mode():
        return

    # Data migration: normalize each legacy formulae string (dict already, "None",
    # or the old no-reliable-separator format) into a proper jsonb object.
    bind = op.get_bind()
    rows = bind.execute(
        sa.text(
            "SELECT projid, formulae_old FROM projects WHERE formulae_old IS NOT NULL"
        )
    ).fetchall()
    for projid, formulae_old in rows:
        formulae_dict = _formulae_str_to_dict(formulae_old)
        bind.execute(
            sa.text(
                "UPDATE projects SET formulae = CAST(:formulae AS JSONB) WHERE projid = :projid"
            ),
            {
                "projid": projid,
                "formulae": (
                    json.dumps(formulae_dict) if formulae_dict is not None else None
                ),
            },
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "formulae")
    op.alter_column("projects", "formulae_old", new_column_name="formulae")
    # ### end Alembic commands ###
