"""image_stats

Revision ID: e69dd0a220ab
Revises: fc9fb059120c
Create Date: 2025-11-24 07:57:23.600638

"""

# revision identifiers, used by Alembic.
revision = "e69dd0a220ab"
down_revision = "fc9fb059120c"

from alembic import op


def upgrade():
    op.execute(
        """
        ALTER TABLE ONLY public.images
            ALTER COLUMN objid SET STATISTICS 10000;
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
