"""organizations table and users type

Revision ID: e6dda08ff48b
Revises: 78b24e7ba52b
Create Date: 2025-01-17 11:45:22.873082

"""

# revision identifiers, used by Alembic.
revision = "e6dda08ff48b"
down_revision = "78b24e7ba52b"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from DB.User import UserType, UserStatus, CHK_STATUS, CHK_TYPE


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "directories", postgresql.ARRAY(sa.String(length=100)), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("type", sa.SmallInteger(), nullable=True))
    op.create_check_constraint("checktype", "users", CHK_TYPE)
    op.create_check_constraint("checkstatus", "users", CHK_STATUS)
    op.execute("UPDATE users SET type={0}".format(UserType.user.value))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("checktype", "users", type_="check")
    op.drop_constraint("checkstatus", "users", type_="check")
    op.drop_column("users", "type")
    op.drop_table("organizations")

    # ### end Alembic commands ###
