"""organizations users relation

Revision ID: e6dda08ff48b
Revises: 78b24e7ba52b
Create Date: 2025-01-17 11:45:22.873082

"""

# revision identifiers, used by Alembic.
revision = "e6dda08ff48b"
down_revision = "78b24e7ba52b"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from DB.User import UserType, UserStatus


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "directories", postgresql.ARRAY(sa.String(length=100)), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("type", sa.String(length=10), nullable=False))
    op.execute("UPDATE users SET type='{0}'".format(UserType.user.value))
    op.execute(
        "UPDATE users SET organisation = (SELECT TRIM(organisation) from users as u1 WHERE u1.id=users.id) "
    )
    op.execute(
        "INSERT INTO organizations (name) SELECT DISTINCT organisation FROM users WHERE organisation IS NOT NULL"
    )

    op.create_foreign_key(
        "users_organization", "users", "organizations", ["organisation"], ["name"]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_organization", "users", type_="foreignkey")
    op.drop_column("users", "type")
    op.drop_table("organizations")
    # ### end Alembic commands ###
