"""similarity search

Revision ID: f38a881a1f6c
Revises: 032dfb7159d5
Create Date: 2024-12-21 17:15:24.676449

"""

# revision identifiers, used by Alembic.
revision = "f38a881a1f6c"
down_revision = "032dfb7159d5"

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Alembic autogenerated is partial
    # op.create_index(
    #     "obj_cnn_features_vector_hv_ivfflat_l2_5k_idx",
    #     "obj_cnn_features_vector",
    #     ["features"],
    #     unique=False,
    #     postgresql_using="ivfflat",
    #     postgresql_with={"lists": 5000},
    # )
    op.execute(
        """
SET LOCAL maintenance_work_mem = '8GB';                                                                                                                   
SET LOCAL max_parallel_maintenance_workers = 8;
CREATE INDEX obj_cnn_features_vector_hv_ivfflat_l2_5k_idx ON obj_cnn_features_vector 
 USING ivfflat ((features::halfvec(50)) halfvec_l2_ops) WITH (lists = 5000)
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "obj_cnn_features_vector_hv_ivfflat_l2_5k_idx",
        table_name="obj_cnn_features_vector",
    )
    # ### end Alembic commands ###
