"""remove project description

Revision ID: fc9fb059120c
Revises: 9f8174c268da
Create Date: 2025-10-13 11:24:39.824079

"""

# revision identifiers, used by Alembic.
revision = "fc9fb059120c"
down_revision = "9f8174c268da"

from alembic import op
import sqlalchemy as sa

move_description_to_comments = """
BEGIN;
UPDATE projects
   SET comments = CONCAT(description,' Comments: ',comments);
COMMIT;
"""
split_comments_description = """
BEGIN;
UPDATE projects
   SET description = split_part(comments,' Comments: ',1), comments= split_part(comments,' Comments: ',2);
COMMIT;
"""


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(move_description_to_comments)
    op.drop_column("projects", "description")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.VARCHAR(), nullable=True))
    op.execute(split_comments_description)
    # ### end Alembic commands ###
