[tox]
envlist = py312
skipsdist = True


[testenv]
# We use deps from app code, not present ones which are for the IDE
deps = -r../../py/requirements.txt
setenv = PYTHONPATH = {env:PYTHONPATH:}{:}../../py
passenv = POSTGRES_HOST,POSTGRES_PORT
allowlist_externals =
    ./mypy.sh
    coverage
commands =
    ./mypy.sh
    coverage erase
# No run of tests in API client which is generated
    coverage run -m pytest --ignore=ecotaxa_cli_py
    coverage report --omit='.tox/*'
    coverage html --omit='.tox/*'
    coverage xml --omit='.tox/*' -o ../../py/coverage.xml
