[tox]
basepython = python3.14
envlist = mypy, coverage
skipsdist = True

[testenv:mypy]
deps = -r {tox_root}/../../py/requirements.txt
change_dir = {tox_root}/../../py
commands =
    mypy --config-file {tox_root}/../../py/mypy.ini .

[testenv:coverage]
deps = -r requirements.txt
setenv = PYTHONPATH = {tox_root}/../../py
passenv = POSTGRES_HOST,POSTGRES_PORT
commands =
    coverage erase
    # No run of tests in API client which is generated
    coverage run -m pytest --ignore=ecotaxa_cli_py
    coverage report --omit='.tox/*'
    coverage html --omit='.tox/*'
    coverage xml --omit='.tox/*' -o ../../py/coverage.xml
