name: build

on:
  push:

jobs:
  docker_back:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: grololo06/ecotaxaback:latest
          file: ./docker/prod_image/Dockerfile
       -
        name: Build and push GPU backend
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: grololo06/ecotaxagpuback:latest
          file: ./docker/gpu_prod_image/Dockerfile          
